finance/urls.py
from django.db import models
from django.urls import path
from django.conf.urls import url
from .models import Category
from .views import (
    # Общее
    HomePageView, 
    AboutPageView, 
    
    # Категории
    CategoryListView,
    CategoryCreateView,
    CategoryUpdateView,
    CategoryDeleteView,

    # Операции
    OperationListView, 
    OperationUpdateView, 
    OperationCreateView, 
    OperationDeleteView,

    # Кошелек
    WalletListView,
    WalletCreateView,
    WalletUpdateView,
    WalletDeleteView,

    returnListCategory,
    returnListWallet
)


urlpatterns = [
    path('about/', AboutPageView.as_view(), name='about'),
    path('', HomePageView.as_view(), name='home'),

    # DAL
    url(r'^operations/add/category-ajax/$', returnListCategory, name='returnListCategory'),
    url(r'^operations/update/category-ajax/$', returnListCategory, name='returnListCategory'),

    url(r'^operations/add/wallet_recipient-ajax/$', returnListWallet, name='returnListWallet'),
    url(r'^operations/update/wallet_recipient-ajax/$', returnListWallet, name='returnListWallet'),

    # Журная операций
    path('operations', OperationListView.as_view(), name='operations'),
    path('operations/update/<int:pk>', OperationUpdateView.as_view(), name='operations-update'),
    path('operations/add/', OperationCreateView.as_view(), name='operations-add'),
    path('operations/delete/<int:pk>', OperationDeleteView.as_view(), name='operations-delete'),

    # Категории
    path('categories', CategoryListView.as_view(), name='categories'),
    path('categories/update/<int:pk>', CategoryUpdateView.as_view(), name='categories-update'),
    path('categories/add/', CategoryCreateView.as_view(), name='categories-add'),
    path('categories/delete/<int:pk>', CategoryDeleteView.as_view(), name='categories-delete'),

    # Кошельки
    path('wallets', WalletListView.as_view(), name='wallets'),
    path('wallets/update/<int:pk>', WalletUpdateView.as_view(), name='wallets-update'),
    path('wallets/add/', WalletCreateView.as_view(), name='wallets-add'),
    path('wallets/delete/<int:pk>', WalletDeleteView.as_view(), name='wallets-delete'),
]

finance_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.decorators.csrf import csrf_exempt
from django.conf.urls import url
from graphene_django.views import GraphQLView
# admin.site.site_header = 'Администрирование'

urlpatterns = [
    
    # url(r"^autocomplete/", include("autocomplete_light.urls")),

    # Django admin
    path('admin/', admin.site.urls),

    # User management
    path('accounts/', include('allauth.urls')),

    # url(r'^chaining/', include("smart_selects.urls")),

    

    # Local apps
    path('', include('finance.urls')),

    # GraphQL
    path('graphql', csrf_exempt(GraphQLView.as_view(graphiql=True))),
]

users/urls.py
from django.urls import path

from .views import SignupPageView


urlpatterns = [
    path('signup/', SignupPageView.as_view(), name='signup'),
]

finance/models.py
import uuid
from django.db import models
from datetime import datetime
from django.contrib.auth import get_user_model, get_user
from django.db.models.deletion import CASCADE, PROTECT
from django.db.models.fields import DecimalField
from django.db.models.query import QuerySet
from django.urls import reverse
# from smart_selects.db_fields import ChainedForeignKey


class Currency(models.Model):
    code = models.CharField(max_length=5, unique=True, db_index=True)
    charactercode = models.CharField(max_length=5, blank=True, null=True)
    title = models.CharField(max_length=150)

    class Meta:
        verbose_name = "Валюта"
        verbose_name_plural = "Валюты"

    def __str__(self):
        return self.charactercode


class Wallet(models.Model):
    title = models.CharField(max_length=150)
    currency = models.ForeignKey(
        Currency, on_delete=PROTECT, verbose_name='Валюта')
    description = models.TextField(blank=True)
    user = models.ForeignKey(
        get_user_model(),
        on_delete=CASCADE,
    )

    def __str__(self):
        return self.title + ' (' + str(self.currency) + ')'

    class Meta:
        verbose_name = "Кошелек"
        verbose_name_plural = "Кошельки"


typeIncome = 'Доход'
typeExpense = 'Расход'
typeTransfer = 'Перевод'

type_choices = [
    (typeExpense, 'Расход'),
    (typeIncome, 'Доход'),
]

type_choices_operation = [
    (typeExpense, 'Расход'),
    (typeIncome, 'Доход'),
    (typeTransfer, 'Перевод'),
]


class Category(models.Model):
    title = models.CharField('Название', max_length=150)
    type = models.CharField(
        max_length=10, choices=type_choices, default=typeExpense)
    user = models.ForeignKey(
        get_user_model(),
        on_delete=CASCADE,
    )

    class Meta:
        verbose_name = "Категории"
        verbose_name_plural = "Категория"
        ordering = ['type', 'title']

    def __str__(self):
        return self.title

    # def chained_relation(self):
    #     return self.operation_set.filter(user = self.request.user)


class Operation(models.Model):
    type = models.CharField('Тип', max_length=10,
                            choices=type_choices_operation, default=typeExpense)
    user = models.ForeignKey(get_user_model(), on_delete=CASCADE)
    # category = ChainedForeignKey(
    #     'Category',
    #     on_delete=PROTECT,
    #     chained_field="type",
    #     chained_model_field="type",
    #     show_all=False,
    #     auto_choose=True,
    #     verbose_name='Категория'
    # )
    category = models.ForeignKey(
        'Category',
        on_delete=PROTECT,
        verbose_name='Категория',
        blank=True,
        null=True)
    date = models.DateTimeField('Дата', default=datetime.now)
    wallet = models.ForeignKey(Wallet, on_delete=PROTECT, verbose_name='Кошелек', related_name='wallet')
    wallet_recipient = models.ForeignKey(
        Wallet, 
        on_delete=PROTECT, 
        verbose_name='На кошелек', 
        related_name='wallet_recipient',
        blank=True,
        null=True)
    sum = models.DecimalField('Сумма', max_digits=15, decimal_places=2)
    description = models.TextField('Описание', blank=True)

    def __str__(self):
        str_type = ': -' if self.type == typeExpense else ': +'
        return str(self.category) + str_type + str(self.sum)

    class Meta:
        verbose_name = "Операция"
        verbose_name_plural = "Операции"
        ordering = ['-date']

finance/forms.py
from email.policy import default
from tabnanny import verbose
from django import forms
from django.forms import ModelForm
from .models import Operation
from datetime import datetime


class OperationCreateForm(ModelForm):
    date = forms.DateTimeField(label='Дата', input_formats=['%d.%m.%Y %H:%M'], initial=datetime.now)
    class Meta:
        model = Operation
        fields = ['sum', 'wallet', 'wallet_recipient', 'type', 'category', 'date', 'description']

class OperationUpdateForm(ModelForm):
    date = forms.DateTimeField(label='Дата', input_formats=['%d.%m.%Y %H:%M'], initial=datetime.now)
    class Meta:
        model = Operation
        fields = ['sum', 'wallet', 'wallet_recipient', 'type', 'category', 'date', 'description']
        

finance/views.py
from django.http.response import JsonResponse
from django.db.models import Q
from django.core.exceptions import ValidationError
from django.views.generic import TemplateView, ListView, CreateView, UpdateView, DeleteView
from dateutil.relativedelta import relativedelta
from django.urls import reverse_lazy, reverse
from django.shortcuts import redirect
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

import json
import datetime

from .forms import OperationCreateForm, OperationUpdateForm
from .calcOfBalances import calculation_of_balances, expenses_by_category, incomes_by_category
from .addFunctions import MonthInWords

from .models import (
    Category,
    Operation,
    Wallet,
    typeIncome
)


class HomePageView(LoginRequiredMixin, TemplateView):
    template_name = 'home.html'

    def get_context_data(self, *args, **kwargs):
        context = super(HomePageView, self).get_context_data(*args, **kwargs)
        
        # Определеяем период для вывода
        today = datetime.datetime.today()
        datePrevMonth = today - relativedelta(months=1)
        date2PrevMonth = today - relativedelta(months=2)
        date3PrevMonth = today - relativedelta(months=3)

        # Определяем общий остаток
        rezult = calculation_of_balances(self.request.user, date3PrevMonth, today)
        context['start_date'] = date3PrevMonth.strftime('%Y-%m-%d')
        context['income_list'] = json.dumps(rezult['income_list'])
        context['expense_list'] = json.dumps(rezult['expense_list'])
        context['balance_list'] = json.dumps(rezult['balance_list'])

        # Название месяцев
        context['name2PrevMonth'] = json.dumps(MonthInWords(date2PrevMonth))
        context['namePrevMonth'] = json.dumps(MonthInWords(datePrevMonth))

        # Доходы
        # Определям доходы по категориям за препредущий месяц
        incomes2PrevMonth = incomes_by_category(self.request.user, date2PrevMonth)
        context['showIncomes2PrevMonth'] = len(incomes2PrevMonth) > 0
        context['incomes2PrevMonth'] = json.dumps(incomes2PrevMonth)
        
        # Определям доходы по категориям за предущий месяц
        incomesOfPrevMonth = incomes_by_category(self.request.user, datePrevMonth)
        context['showIncomesPrevMonth'] = len(incomesOfPrevMonth) > 0
        context['incomesPrevMonth'] = json.dumps(incomesOfPrevMonth)
        
        # Определям доходы по категориям за текущий месяц
        incomesOfCurrentMonth = incomes_by_category(self.request.user, today)
        context['incomesOfCurrentMonth'] = json.dumps(incomesOfCurrentMonth)
        print(incomesOfCurrentMonth)

        # Расходы
        # Определям расходы по категориям за препредущий месяц
        expenses2PrevMonth = expenses_by_category(self.request.user, date2PrevMonth)
        context['showExpenses2PrevMonth'] = len(expenses2PrevMonth) > 0
        context['expenses2PrevMonth'] = json.dumps(expenses2PrevMonth)
        
        # Определям расходы по категориям за предущий месяц
        expensesOfPrevMonth = expenses_by_category(self.request.user, datePrevMonth)
        context['showExpensesPrevMonth'] = len(expensesOfPrevMonth) > 0
        context['expensesPrevMonth'] = json.dumps(expensesOfPrevMonth)

        # Определям расходы по категориям за текущий месяц
        expensesOfCurrentMonth = expenses_by_category(self.request.user, today)
        context['expensesOfCurrentMonth'] = json.dumps(expensesOfCurrentMonth)

        # Отображение остатков по каждому кошельку
        wallets = Wallet.objects.filter(user=self.request.user)
        list_wallets = []
        for currentWallet in wallets:
            rezult = calculation_of_balances(self.request.user, datePrevMonth, today, currentWallet)
            list_wallets.append({
                'id': currentWallet.id, 
                'title': currentWallet.title,
                'income_list': rezult['income_list'],
                'expense_list': rezult['expense_list'],
                'balance_list': rezult['balance_list'],
            })
            
        context['start_date_1m'] = datePrevMonth.strftime('%Y-%m-%d')
        context['wallets'] = wallets
        context['list_wallets'] = json.dumps(list_wallets)
        
        return context


class AboutPageView(TemplateView):
    template_name = 'about.html'


class CategoryListView(LoginRequiredMixin, ListView):
    model = Category
    context_object_name = 'categories'

    def get_queryset(self):
        queryset = Category.objects.filter(user=self.request.user)
        return queryset


class CategoryUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Category
    fields = ['title', 'type']
    template_name_suffix = '_update_form'
    success_url = reverse_lazy('categories')

    def test_func(self):
        object = self.get_object()
        return object.user == self.request.user


class CategoryCreateView(CreateView):
    model = Category
    fields = ['title', 'type']
    context_object_name = 'category'
    success_url = reverse_lazy('categories')

    def form_valid(self, form):
        object = form.save(commit=False)
        object.user = self.request.user
        object.save()
        return super(CategoryCreateView, self).form_valid(form)


class CategoryDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Category
    context_object_name = 'category'
    success_url = reverse_lazy('categories')

    def test_func(self):
        object = self.get_object()
        return object.user == self.request.user


class OperationListView(LoginRequiredMixin, ListView):
    model = Operation
    context_object_name = 'Operations'
    paginate_by = 30

    def get_queryset(self):
        user = self.request.user
        try:
            search_text = self.request.GET.get('search_text')
        except:
            search_text = ''
        if search_text != '' and search_text != None:
            queryset = Operation.objects.filter(
                (Q(category__title__icontains=search_text) 
                    | Q(wallet__title__icontains=search_text) 
                    | Q(wallet_recipient__title__icontains=search_text)
                    | Q(description__icontains=search_text)),
                user=user)
        else:
            queryset = Operation.objects.filter(user=user)
        
        return queryset

class OperationUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Operation
    form_class = OperationUpdateForm
    # fields = ['sum', 'wallet', 'type', 'category', 'wallet_recipient', 'date', 'description']
    template_name_suffix = '_update_form'
    success_url = reverse_lazy('operations')
    context_object_name = 'operation'

    def get_context_data(self, **kwargs):
        context = super(OperationUpdateView, self).get_context_data(**kwargs)
        context['form'].fields['wallet'].queryset = Wallet.objects.filter(user=self.request.user)
        context['form'].fields['wallet_recipient'].queryset = Wallet.objects.filter(user=self.request.user)
        return context

    def test_func(self):
        object = self.get_object()
        return object.user == self.request.user

class OperationCreateView(CreateView):
    model = Operation
    # fields = ['sum', 'wallet', 'type', 'category', 'date', 'description']
    context_object_name = 'operation'
    form_class = OperationCreateForm
    success_url = reverse_lazy('operations')
    template_name_suffix = '_form'

    def get_context_data(self, **kwargs):
        context = super(OperationCreateView, self).get_context_data(**kwargs)
        context['form'].fields['wallet'].queryset = Wallet.objects.filter(user=self.request.user)
        context['form'].fields['wallet_recipient'].queryset = Wallet.objects.filter(user=self.request.user)
        
        # Передаем на форму куда вернуться, если нажали "Назад"
        if 'operations' in self.request.GET.get('next', '/'):
            context['next'] = '/operations'
            self.success_url = reverse_lazy('operations')
        else:
            context['next'] = '/'
            self.success_url = reverse_lazy('home')
        return context

    def post(self, request, *args, **kwargs):
        if "addMore" in request.POST:
            self.success_url = reverse_lazy('operations-add')
            if 'operations' in request.GET.get('next', '/'):
                self.success_url += '?next=operations'
            else:
                self.success_url += '?next=home'
            if 'addIncome' in request.GET:
                self.success_url += '&addIncome'
            return super(OperationCreateView, self).post(request, *args, **kwargs)
        else:
            if 'operations' in request.GET.get('next', '/'):
                self.success_url = reverse_lazy('operations')
            else:
                self.success_url = reverse_lazy('home')
            return super(OperationCreateView, self).post(request, *args, **kwargs)

    def form_valid(self, form):
        object = form.save(commit=False)
        object.user = self.request.user
        object.save()
        # Тест. Здесь тоже работает, но не знаю где лучше использовать, пока оставлю в post
        # if "addMore" in self.request.POST:
        #     self.success_url = reverse_lazy('operations-add')
        #     return super(OperationCreateView, self).form_valid(form)
        # else:
        #     return super(OperationCreateView, self).form_valid(form)
        return super(OperationCreateView, self).form_valid(form)

    # def get_success_url(self):
    #     print(f"HTTP_REFERER = {self.request.POST}")
    #     return self

class OperationDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Operation
    context_object_name = 'operation'
    success_url = reverse_lazy('operations')

    def test_func(self):
        object = self.get_object()
        return object.user == self.request.user


class WalletListView(LoginRequiredMixin, ListView):

templates/finance/category_confirm_delete.html
{% extends '_base.html' %}

{% load crispy_forms_tags %}

{% block title %}Удаление категорий{% endblock title %}

{% block content %} 
<div class="form-row">
    <div class="col-md-6"><h4>Категория:</h4></div>
    <div class="col-md-6"><a class="float-right" href="{% url 'categories' %}">Отмена</a></div>
</div>
<form method="POST">
    {% csrf_token %}
    {{ form|crispy}}
    <p>Вы уверены что хотите удалить категорию "{{ category }}"?</p>
    <input class="btn btn-danger" type="submit" value="Удалить">
</form>

{% endblock content %}

templates/finance/category_form.html
{% extends '_base.html' %}

{% load crispy_forms_tags %}

{% block title %}Добавление категорий{% endblock title %}

{% block content %} 
<div class="form-row">
    <div class="col-md-6"><h4>Категория:</h4></div>
    <div class="col-md-6"><a class="float-right" href="{% url 'categories' %}">Отмена</a></div>
</div>
<form method="POST">
    {% csrf_token %}
    {{ form|crispy}}
    <input class="btn btn-primary" type="submit" value="Сохранить">
</form>

{% endblock content %}

templates/finance/category_list.html
{% extends '_base.html' %}

{% block title %}Все поступления{% endblock title %}

{% block content %} 
    
    <div class="container">
        <div class="my-1">
            <div class="form-row d-flex p-2 align-items-center">
                <div class="col"><h5>Категории:</h5></div>
                <div class="col">
                    <a class="btn btn-primary float-right" href="{% url 'categories-add' %}?next={{request.path}}" role="button">Добавить</a>
                </div>
            </div>
        </div>
        <table class="table table-hover">
            <thead>
                <tr>
                  <th scope="col">Название</th>
                  <th scope="col">Тип</th>
                  <th scope="col"></th>
                </tr>
            </thead>
            {% for category in categories %}
                <tr>
                    <td>{{ category.title }}</td>
                    <td>{{ category.type }}</td>
                    <td><a class="text-danger" href="{% url 'categories-update' category.id %}">Редактировать</a></td>
                </tr>
            {% endfor %} 
        </table>   
    </div>
    
{% endblock content %}

templates/finance/category_update_form.html
{% extends '_base.html' %}

{% load crispy_forms_tags %}

{% block title %}Редактирование категорий{% endblock title %}

{% block content %}
<div class="form-row">
    <div class="col-md-6"><h4>Категория:</h4></div>
    <div class="col-md-6"><a class="float-right" href="{% url 'categories' %}">Назад</a></div>
</div>

<form method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="form-row">
        <div class ="col-md-6">
            <input class="btn btn-primary" type="submit" value="Сохранить">
        </div>
        <div class="col-md-6">
            <a class="btn btn-danger float-right" href="{% url 'categories-delete' category.id %}">Удалить</a>
        </div>
    </div>
</form>

{% endblock content %}

templates/finance/operation_confirm_delete.html
{% extends '_base.html' %}

{% load crispy_forms_tags %}

{% block title %}Удаление операции{% endblock title %}

{% block content %} 
<div class="form-row">
    <div class="col-md-6"><h4>Операция:</h4></div>
    <div class="col-md-6"><a class="float-right" href="{% url 'operations' %}">Отмена</a></div>
</div>
<form method="POST">
    {% csrf_token %}
    {{ form|crispy}}
    <p>Вы уверены что хотите удалить операцию "{{ operation }}" от {{ operation.date }}?</p>
    <input class="btn btn-danger" type="submit" value="Удалить">
</form>

{% endblock content %}

templates/finance/operation_form.html
{% extends '_base.html' %}

{% load crispy_forms_tags %}
{% load static %}
{% load humanize %}

{% block title %}Добавление операции{% endblock title %}

{% block content %}
<div class="form-row">
  <div class="col-md-6">
    <h4>Операция:</h4>
  </div>
  <div class="col-md-6">
    <a class="float-right" href="{{ next|safe }}">Отмена</a></div>
</div>
<form id="operation_form" method="POST" action="">
  {% csrf_token %}
  {% load humanize %}
  <div class="row">
    <div class="col-6">
      {{ form.sum|as_crispy_field|intcomma }}
    </div>
    <div class="col-6">
      {{ form.wallet|as_crispy_field }}
    </div>
  </div>
  <div class="row">
    <div class="col-6">
      {{ form.type|as_crispy_field }}
    </div>
    <div class="col-6">
      {{ form.category|as_crispy_field }}
      {{ form.wallet_recipient|as_crispy_field }}
    </div>
  </div>
  <div class="row">
    <div class="col-6">
        {{ form.date|as_crispy_field }}
    </div>
  </div>
  <div id="div_id_description" class="form-group">
    <label for="id_description" class="">Описание</label>
    <div class="">
      <textarea name="description" cols="40" rows="5" class="textarea form-control" id="id_description"></textarea>
    </div>
  </div>
  <input class="btn btn-primary" type="submit" value="Сохранить">
  <input class="btn btn-link" type="submit" name="addMore" value="Сохранить и добавить еще..">
</form>
{% endblock content %}


{% block footer %}

<script src="{% static 'js/select.js' %}"></script>
<script>
  $(function () {
    $("#id_date").datetimepicker({
      format: 'd.m.Y H:i',
    });
  });
</script>

{% endblock footer %}

templates/finance/operation_list.html
{% extends '_base.html' %}

{% block title %}Журная операций{% endblock title %}

{% block content %}

<div class="container">
    <div class="my-1">
        <div class="form-row d-flex p-2 align-items-center">
            <div class="col">
                <h5>Журнал операций:</h5>
            </div>
            <div class="col">
                <form method='get' action="{% url 'operations' %}">
                    <input class="form-control" type="search" size="30" name="search_text"
                        value="{{ request.GET.search_text }}" id="search_text" placeholder="Поиск">
                </form>
            </div>
            <div class="col">
                <a class="btn btn-primary float-right"
                    href="{% url 'operations-add' %}?next={% firstof request.path '/' %}" role="button">Добавить</a>
            </div>
        </div>
    </div>

    <table class="table table-hover">
        {% load humanize %}
        <thead>
            <tr class="info">
                <th scope="col">Тип</th>
                <th scope="col">Кошелек</th>
                <th scope="col">Сумма</th>
                <th scope="col">Категория/Кошелек</th>
                <!-- <th scope="col">Полkьзователь</th> -->
                <th scope="col">Дата</th>
                <th scope="col">Описание</th>
            </tr>
        </thead>
        {% for operation in Operations %}
        <tr>
            <td><a href="{% url 'operations-update' operation.id %}">{{ operation.type }}</a></td>
            <td>{{ operation.wallet }}</td>
            <td align="right">{{ operation.sum }}</td>
            <td>{{ operation.category|default_if_none:"" }}{{ operation.wallet_recipient|default_if_none:"" }}</td>
            <!-- <td>{{ operation.user }}</td> -->
            <td>{{ operation.date }}</td>
            <td>{{ operation.description }}</td>
        </tr>
        {% endfor %}
    </table>

    {% if is_paginated %}
    <div class="pagination">
        <ul class="pagination">
            {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link"
                    href="?page={{ page_obj.previous_page_number }}{% if request.GET.search_text %}&search_text={{request.GET.search_text}}{%endif%}">Предыдущая</a>
            </li>
            {% endif %}
            {% for num_current_page in page_obj.paginator.page_range %}
            {% if page_obj.number == num_current_page %}
            <li class="page-item active"><span class="page-link">{{ num_current_page }}<span
                        class="sr-only">(current)</span></span></li>
            {% else %}
            <li class="page-item"><a class="page-link"
                    href="?page={{ num_current_page }}{% if request.GET.search_text %}&search_text={{request.GET.search_text}}{%endif%}">{{ num_current_page }}</a>
            </li>
            {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link"
                    href="?page={{ page_obj.next_page_number }}{% if request.GET.search_text %}&search_text={{request.GET.search_text}}{%endif%}">Следующая</a>
            </li>
            {% endif %}
        </ul>
    </div>
    {% endif %}
</div>

{% endblock content %}

templates/finance/operation_update_form.html
{% extends '_base.html' %}

{% load crispy_forms_tags %}
{% load static %}

{% block title %}Редактирование операций{% endblock title %}

{% block content %}
<div class="form-row">
  <div class="col-md-6">
    <h4>Операция:</h4>
  </div>
  <div class="col-md-6"><a class="float-right" href="{% url 'operations' %}">Назад</a></div>
</div>

<form method="POST">
  {% csrf_token %}
  {% load humanize %}
  <div class="row">
    <div class="col-6">
      {{ form.sum|as_crispy_field }}
    </div>
    <div class="col-6">
      {{ form.wallet|as_crispy_field }}
    </div>
  </div>
  <div class="row">
    <div class="col-6">
      {{ form.type|as_crispy_field }}
    </div>
    <div class="col-6">
      {{ form.category|as_crispy_field }}
      {{ form.wallet_recipient|as_crispy_field }}
    </div>
  </div>
  <div class="row">
    <div class="col-6">
      {{ form.date|as_crispy_field }}
    </div>
  </div>
  <div id="div_id_description" class="form-group">
    <label for="id_description" class="">Описание</label>
    <div class="">
      <textarea name="description" cols="40" rows="5" class="textarea form-control" id="id_description">{{ operation.description }}</textarea>
    </div>
  </div>
  <div class="form-row">
    <div class="col-md-6">
      <input class="btn btn-primary" type="submit" value="Сохранить">
    </div>
    <div class="col-md-6">
      <a class="btn btn-danger float-right" href="{% url 'operations-delete' operation.id %}">Удалить</a>
    </div>
  </div>
</form>


{% endblock content %}


{% block footer %}

<script src="{% static 'js/select.js' %}"></script>
<script>
  $(function () {
    $("#id_date").datetimepicker({
      format: 'd.m.Y H:i:s',
    });
  });
</script>

{% endblock footer %}

templates/finance/wallet_confirm_delete.html
{% extends '_base.html' %}

{% load crispy_forms_tags %}

{% block title %}Удаление кошелька{% endblock title %}

{% block content %} 
<div class="form-row">
    <div class="col-md-6"><h4>Кошелек:</h4></div>
    <div class="col-md-6"><a class="float-right" href="{% url 'wallets' %}">Отмена</a></div>
</div>
<form method="POST">
    {% csrf_token %}
    {{ form|crispy}}
    <p>Вы уверены что хотите удалить кошелец "{{ wallet }}"?</p>
    <input class="btn btn-danger" type="submit" value="Удалить">
</form>

{% endblock content %}

templates/finance/wallet_form.html
{% extends '_base.html' %}

{% load crispy_forms_tags %}

{% block title %}Добавление кошелька{% endblock title %}

{% block content %} 
<div class="form-row">
    <div class="col-md-6"><h4>Кошелек:</h4></div>
    <div class="col-md-6"><a class="float-right" href="{% url 'wallets' %}">Отмена</a></div>
</div>
<form method="POST">
    {% csrf_token %}
    {{ form|crispy}}
    <input class="btn btn-primary" type="submit" value="Сохранить">
</form>

{% endblock content %}

templates/finance/wallet_update_form.html
{% extends '_base.html' %}

{% load crispy_forms_tags %}

{% block title %}Редактирование кошелька{% endblock title %}

{% block content %}
<div class="form-row">
    <div class="col-md-6"><h4>Кошелек:</h4></div>
    <div class="col-md-6"><a class="float-right" href="{% url 'wallets' %}">Назад</a></div>
</div>

<form method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="form-row">
        <div class ="col-md-6">
            <input class="btn btn-primary" type="submit" value="Сохранить">
        </div>
        <div class="col-md-6">
            <a class="btn btn-danger float-right" href="{% url 'wallets-delete' wallet.id %}">Удалить</a>
        </div>
    </div>
</form>


{% endblock content %}